#PBS -l nodes=1:ppn=1
#PBS -l walltime=24:00:00
#PBS -l pvmem=10GB
#PBS -l mem=10GB
#PBS -N cs82
#PBS -q batch
#PBS -o data/logs
#PBS -e data/logs
#PBS -m abe

echo HOME dir is $HOME

#cd /home/dstn/tractor-trunk
#BAND=i
#python -u cs82.py -l -b $BAND --prefix cs82-${BAND}2- --decs 4 --ras 50

cd /home/dstn/tractor-git
#python -u cs82.py -l S82p40p S82p41p S82p42p S82p43p --decs 4 --ras 50

python -u cs82.py -l --decs 4 --ras 50 W4m0m1 W4m0m2 W4m1m1 W4m1m2 W4p1m1 W4p1m2 W4p2m1 W4p2m2


